[package]
authors = ["LeakyBucket <DamnBigMan@gmail.com>"]
edition = "2018"
name = "filler"
version = "0.1.0"
[dependencies]
clap = "*"
regex = "*"
rusoto_core = "0.41.0"
rusoto_ssm = "0.41.0"
serde_json = "1.0.41"

[dependencies.serde]
features = ["derive"]
version = "1.0.102"
